### ISSUE TITLE
DC motor Simulation @Bug

### ISSUE THREAD

**Issue by WinstonHChou** [jsimpso81/WPIlibMathLabVIEW#162] opened 2023-10-22 09:58 UTC
I believe there a bug with Velocity_RPM's unit in DC motor simulation execute.
Here's a small expr I did that lead me to the doubt:
1. Create a 20ms loop to place a DC motor simulator execute vi.
2. give any motor power output
3. Using current value of Rotation minus the previous value, then divide it by / 20 ms
4. I find that the result approximately equals to the value of RPM

So, Shouldn't the unit of velocity be Rotation per sec?

**Comment by jsimpso81** [comment] 2023-11-08 22:07
Thanks.  I will look into this.  Is the problem with DCMotorSim_Execute.VI ?

Do you have a test program or screen shots that you can add here to help diagnose the issue?

Thanks !

**Comment by jsimpso81** [comment] 2023-11-08 22:41
I confirmed the bug, but it appears to be different.   It looks like the RPM calculation is correct.  The rotations calculation is off by a factor of 60.    (Take the current result of rotations and divide it by 60.)   Internally everything is in radians and radians/sec.   The conversion to RPM appears to be correct but the conversion to rotations is using the rad/sec to rpm conversion which is wrong.

Also if you are using the menu macro, there is a bug here too.  The simulated battery voltage VI should have a constant 12 as the "nominal voltage" input.  The macro uses the current simulated voltage which results in the voltage being driven down to 0 after a period of time.

**Comment by jsimpso81** [comment] 2023-11-08 22:44
![dc-motor-sim-bug-snippet](https://github.com/jsimpso81/WPIlibMathLabVIEW/assets/60305400/c6baf965-c592-479a-ac19-d826a795bcb3)

**Comment by WinstonHChou** [comment] 2023-11-08 23:25
Thanks for identify the issues!!
How long does it take to update this correction?

**Comment by jsimpso81** [comment] 2023-11-09 07:49
Fixed.  Will be in the 3.08 release.  I'll probably publish it tomorrow.  (Also if you are using the battery simulation, the nominal voltage value is a constant.  The macro was wrong.  It is fixed now too.)    I tested it by simulating a CIM motor.  The RPM value matched what I expected.  I let it run for a minute and the rotations also matched what I expected -- not exact -- but fairly close.

**Closed by jsimpso81** 2023-11-09 07:49 UTC
Labels: bug, good first issue

**Comment by jsimpso81** [comment] 2023-11-11 12:38
In case you didn’t see it, a new release was published with the fix 

On Nov 8, 2023, at 6:25 PM, Winston ***@***.***> wrote:

﻿
Thanks for identify the issues!!
How long does it take to update this correction?
